### ISSUE TITLE
npm install fails with node v13.5.0

### ISSUE THREAD

**Issue by samsonho** [rupnikj/nodeimu#11]
Hello Rupnikj,

I'm encountering build errors on my Raspberry Pi 4 with (non-LTS) v13.5.0, using

$ git clone ... --recursive
$ npm install

I pretty sure V8 has removed the Handle Class from the V8 namespace/class parent since v12. Just wondering if you want to have this fixed for Non-LTS versions of node (as you might not want to support it.) Should I branch and send a pull request (if I find time). Thanks for reading.

Cheers,
Samson

[nodeimu_errors.txt](https://github.com/rupnikj/nodeimu/files/3981726/nodeimu_errors.txt)

**Comment by rupnikj** [comment]
Help would be appreciated, I currently don't have time to upgrade v8 stuff:)

**Comment by rupnikj** [comment]
Fixed by @jyutzio
