### ISSUE TITLE
Publish latest changes to npm

### ISSUE THREAD

**Issue by paulolc** [rupnikj/nodeimu#12]
nodeimu on npm does not have the latest changes. Namely the node-gyp update which updates the minimatch dependency and resolves its vulnerability on all dependent projects like node-sense-hat.

Please republish nodeimu to npm with the latest changes.

**Comment by jyutzio** [comment]
I agree it would be very helpful, especially considering there are other npm packages which rely on this one

**Comment by rupnikj** [comment]
I updated dependencies and republished. @jyutzio @paulolc can you check?

**Comment by jyutzio** [comment]
I can confirm it works. Thanks rupnikj, that was very quick. :+1:
