### ISSUE TITLE
Can't install nodeimu

### ISSUE THREAD

**Issue by thomvand26** [rupnikj/nodeimu#9]
I can't get nodeimu installed on my raspberry pi.
`npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

When I run `npm view minimatch version`
it prints `3.0.4`

`node -v`
`v10.9.0`

`nodejs -v`
`v12.8.0`

`npm -v`
`6.10.3`

**Comment by rupnikj** [comment]
Should be resolved by @jyutzio
